version: '3'
services:
  app:
    container_name: node-mongo
    image: kavisuresh/employee
    ports:
      - '8888:8888'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
