apiVersion: v1
kind: Service
metadata:
  labels:
    run: mongo
  name: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: mongo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongo
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
