apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: mfts
spec:
  acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: harishbali1997@gmail.com
   privateKeySecretRef:
     name: letsencrypt-prod
     http01: {}